### ISSUE TITLE
Upgrade to sprintf 7.0.0

### ISSUE THREAD

**Issue by ndawod** [bigflood/dartexif#38]
`Because xyz_app depends on exif 3.1.2 which depends on sprintf ^6.0.0, sprintf ^6.0.0 is required.`

`sprintf` is already at a major version bump (`7.0.0`), would be nice to get this plugin also synced with that.

**Comment by vixez** [comment]
I created a fork for this so you can continue using exif

```
  exif:
    git:
      url: git@github.com:vixez/dartexif.git
      ref: master
```
